package com.niu.protect.network;

import android.os.Environment;
import java.io.File;
public final class StudentBaseUrl {
    public static final String BASE_URL = "https://www.xinyu126.com/monitor";
    public static final String BASE_URL_JIAOWU = "http://139.9.121.96:8080/h5/#/?token=";
    public static final String GET_SMALLPROGRAMLIST = "v1/apps/smallProgramList";
    public static final String GET_TEMPORARY_UNBINDINFO = "v1/apps/getTemporaryUnBindInfo";
    public static final String PERMISSION_RESULT = "v1/mobilePermission/setPermissionResult";
    public static final String PERMISSION_SETTING = "v1/mobilePermission/setMobilePermission";
    public static final String SYSTEM_CONFIG = "v1/appMarket/applicationMarket";
    public static final String URL_USER = "http://app.3985.site/html/regUserAgree.html";
    public static final String URL_YINSI = "http://app.3985.site/html/privacyPolicy.html";
    public static final String USER_CODE_LOGIN = "v1/members/studentIdCodeLogin";
    public static final String USER_CONTROLLER_STATUS = "v1/status/setUserControlStatus";
    public static final String USER_SEND_VCODE = "v1/members/sendVCode";
    public static final String USER_WHITE_APP_LIST = "v1/appWhitelist/studentWhitelist";
    public static final String WEBSOCKET_URI = "wss://ws.xinyu126.com:9090/monitor/";
    public static final String appBlacklists_studentBlacklist = "v1/appBlacklists/studentBlacklist";
    public static final String appBlacklists_systemBlacklist = "v1/appBlacklists/systemBlacklist";
    public static final String appBlacklists_systemWhiteList = "v1/appBlacklists/systemWhitelist";
    public static final String appRecords_statistics = "v1/appRecords/statistics";
    public static final String appUseRecords_appuserecord = "v1/appUseRecords/app-use-record-list";
    public static final String appUseRecords_batchAddRecord = "v1/appUseRecords/batchAddRecord";
    public static final String applicationPrograms_general = "v1/applicationPrograms/general";
    public static final String apps_appList = "v1/apps/appList";
    public static final String apps_batchAddApp = "v1/apps/batchAddApp";
    public static final String apps_batchAddApp_first = "v1/apps/firstBatchAddApp";
    public static final String apps_batchdelete = "v1/apps/batch-delete";
    public static final String appversion_info = "v1/app-version/info";
    public static final String auto_setting_content = "v1/power/findByCondition";
    public static final File baseFile = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS);
    public static final String baseurl = StudentBaseUrl.BASE_URL+"/api/";
    public static final String baseweb = "http://139.9.121.96:8289/";
    public static final String brwDownUrl = "https://stu-mob-mon.oss-cn-hangzhou.aliyuncs.com/app/apk/browser20.apk";
    public static final String brwPageName = "com.qjj.studydainty";
    public static final String feedbacks_add = "v1/feedbacks/add";
    public static final String fileInfos_upload = "v1/fileInfos/upload";
    public static final String fileInfos_uploadZip = "v1/fileInfos/uploadZip";
    public static final String imgurl = StudentBaseUrl.BASE_URL;
    public static final String inspirationalMottos_random = "v1/inspirationalMottos/random";
    public static final String members_getMemberInfo = "v1/members/getMemberInfo";
    public static final String members_sendVCode = "v1/members/sendVCode";
    public static final String parents_statistic = "v1/parents/statistic";
    public static final String patternParents_holidayModel = "v1/patternParents/holidayModel";
    public static final String patternParents_query = "v2/patternParents/query";
    public static final String patternParents_schoolModel = "v1/patternParents/schoolModel";
    public static final String patternTeachers_query = "v2/patternTeachers/query";
    public static final String patternTeachers_querybyteacherid = "v2/patternTeachers/query-by-teacher-id";
    public static final String patternTeachers_schoolModel = "v1/patternTeachers/schoolModel";
    public static final String students_qrCodeBind = "v1/students/qrCodeBind";
    public static final String students_update = "v1/students/update";
    public static final String traceGatherRecords_saveGatherRecords = "v1/traceGatherRecords/saveGatherRecords";
    public static final String traceRecords_updateTrace = "v1/traceRecords/updateTrace";
    public static final String user_changePwd = "v1/members/reset";
    public static final String user_exit = "v1/members/exit";
    public static final String user_login = "v1/members/login";
    public static final String user_register = "v1/members/register";
}
